FROM nginx:latest
LABEL 'MAINTAINER' = 'Oleg V. Ivantsov' 'EMAIL' = 'o.v.ivantsov@gmail.com'

RUN apt-get update && apt-get install -y \
    mc \
    nano \
    software-properties-common \
    python3-certbot-nginx
